
CREATE DATABASE iot;
USE iot;
CREATE TABLE datasensor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nhietdo FLOAT NOT NULL,
    doam FLOAT NOT NULL,
    anhsang FLOAT NOT NULL,
    thoigian DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE lichsu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    thietbi VARCHAR(100) NOT NULL,
    trangthai VARCHAR(100) NOT NULL,
    thoigian DATETIME DEFAULT CURRENT_TIMESTAMP
);
