DROP DATABASE iot2;
CREATE DATABASE iot2;
USE iot2;
CREATE TABLE datasensor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nhietdo FLOAT NOT NULL,
    doam FLOAT NOT NULL,
    anhsang INTEGER NOT NULL,
    windspeed INTEGER NOT NULL,
    thoigian DATETIME NOT NULL
);
CREATE TABLE lichsu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    thietbi VARCHAR(100) NOT NULL,
    trangthai VARCHAR(100) NOT NULL,
    thoigian DATETIME NOT NULL
);
